### ISSUE TITLE
problem with price_collector.p

### ISSUE THREAD

**Issue by madbuda** [philippnormann/chia-monitor#23]
Grabbed the latest update, DB update failed... renamed history.sqlite and created a new one.

When I run it I get the following error now.

```
madbuda@tank:~/chia-monitor$ pipenv run python -m monitor
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/madbuda/chia-monitor/monitor/__main__.py", line 14, in <module>
    from monitor.collectors.price_collector import PriceCollector
  File "/home/madbuda/chia-monitor/monitor/collectors/price_collector.py", line 17, in <module>
    class PriceCollector(Collector):
  File "/home/madbuda/chia-monitor/monitor/collectors/price_collector.py", line 21, in PriceCollector
    async def create(_root_path: Path, _net_config: Dict, event_queue: Queue[ChiaEvent]) -> Collector:
TypeError: 'type' object is not subscriptable
```

**Comment by madbuda** [comment]
rolled back to afbd24f580547bc4335e6c9aef966d7bdbd34715 and everything works fine

**Comment by philippnormann** [comment]
Latest commit should fix this. Can you please retry and tell me if it's working for you?

**Comment by philippnormann** [comment]
And do you maybe still have the error logs from the failed DB migration?

**Comment by madbuda** [comment]
that did the trick, I copied back the old history file and still get the following error.

 ```
pipenv run alembic upgrade head
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 2d3d4960ffe8 -> a5503c1613b5, Switch to autoincrement id as pk for farming
_info_events
Traceback (most recent call last):
  File "/home/madbuda/.local/share/virtualenvs/chia-monitor-eqsmFBji/lib/python3.8/site-packages/alembic/operations/batch.py
", line 569, in drop_constraint
    const = self.named_constraints.pop(const.name)
KeyError: 'pk_farming_info_events'
...
ValueError: No such constraint: 'pk_farming_info_events'
```

**Comment by philippnormann** [comment]
Okay, I think I know where this is coming from. Can you try running the migration again using https://github.com/philippnormann/chia-monitor/commit/2c52c15a43d6c19418fee8c0251ab9e3e8b3acf9?

**Comment by madbuda** [comment]
That did the trick! TY
